kind: Template
apiVersion: v1
metadata:
  labels:
    app: kubernetes-image-puller
  name: kubernetes-image-puller
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: k8s-image-puller
  type: Opaque
  data:
    IMAGES: ${IMAGES}
    DAEMONSET_NAME: ${DAEMONSET_NAME}
    CACHING_INTERVAL_HOURS: ${CACHING_INTERVAL_HOURS}
    NAMESPACE: ${NAMESPACE}
    CACHING_MEMORY_REQUEST: ${CACHING_MEMORY_REQUEST}
    CACHING_MEMORY_LIMIT: ${CACHING_MEMORY_LIMIT}
    NODE_SELECTOR: ${NODE_SELECTOR}
parameters:
- name: IMAGES
  value: >
      catalog-spring-boot=quay.io/mcouliba/catalog-spring-boot:3.1_debugging;
      gateway-vertx=quay.io/mcouliba/gateway-vertx:3.1_debugging;
      inventory-quarkus=quay.io/mcouliba/inventory-quarkus:3.1_debugging;
      web-nodejs=quay.io/mcouliba/web-nodejs:3.1_debugging;
- name: DAEMONSET_NAME
  value: "kubernetes-image-puller"
- name: CACHING_INTERVAL_HOURS
  value: "1"
- name: NAMESPACE
  value: "k8s-image-puller"
- name: CACHING_MEMORY_REQUEST
  value: "10Mi"
- name: CACHING_MEMORY_LIMIT
  value: "20Mi"
- name: NODE_SELECTOR
  value: "{}"
